### ISSUE TITLE
taskExtract - instantiate FilesystemStack directly

### ISSUE THREAD

**Issue by Sweetchuck** [consolidation/robo#1088]
### Steps to reproduce
Use the taskExtract() task to extract a *.bz2 file with a `to` directory which is on another volume than the CWD is. 

### Expected behavior
Flawless extract.

### Actual behavior
```
PHP Fatal error:  Uncaught Error: Call to a member function newBuilder() on null in /.../my-project-01/vendor/consolidation/robo/src/Common/BuilderAwareTrait.php:51
Stack trace:
#0 /.../my-project-01/vendor/consolidation/robo/src/Task/Filesystem/FilesystemStack.php(149): Robo\Task\Filesystem\FilesystemStack->collectionBuilder()
#1 /.../my-project-01/vendor/consolidation/robo/src/Task/Filesystem/FilesystemStack.php(122): Robo\Task\Filesystem\FilesystemStack->crossVolumeRename()
#2 [internal function]: Robo\Task\Filesystem\FilesystemStack->_rename()
#3 /.../my-project-01/vendor/consolidation/robo/src/Task/StackBasedTask.php(230): call_user_func_array()
#4 /.../my-project-01/vendor/consolidation/robo/src/Task/StackBasedTask.php(207): Robo\Task\StackBasedTask->callTaskMethod()
#5 /.../my-project-01/vendor/consolidation/robo/src/Task/Archive/Extract.php(135): Robo\Task\StackBasedTask->run()
#6 /.../my-project-01/vendor/consolidation/robo/src/Collection/CompletionWrapper.php(91): Robo\Task\Archive\Extract->run()
#7 /.../my-project-01/vendor/consolidation/robo/src/Collection/Collection.php(666): Robo\Collection\CompletionWrapper->run()
#8 /.../my-project-01/vendor/consolidation/robo/src/Collection/Collection.php(568): Robo\Collection\Collection->runSubtask()
#9 /.../my-project-01/vendor/consolidation/robo/src/Collection/Collection.php(538): Robo\Collection\Collection->runTaskList()
#10 /.../my-project-01/vendor/consolidation/robo/src/Collection/Collection.php(518): Robo\Collection\Collection->runWithoutCompletion()
#11 /.../my-project-01/vendor/consolidation/robo/src/Collection/CompletionWrapper.php(91): Robo\Collection\Collection->run()
#12 /.../my-project-01/vendor/consolidation/robo/src/Collection/Collection.php(666): Robo\Collection\CompletionWrapper->run()
#13 /.../my-project-01/vendor/consolidation/robo/src/Collection/Collection.php(568): Robo\Collection\Collection->runSubtask()
#14 /.../my-project-01/vendor/consolidation/robo/src/Collection/Collection.php(538): Robo\Collection\Collection->runTaskList()
#15 /.../my-project-01/vendor/consolidation/robo/src/Collection/Collection.php(518): Robo\Collection\Collection->runWithoutCompletion()
#16 /.../my-project-01/vendor/consolidation/robo/src/Collection/CollectionBuilder.php(609): Robo\Collection\Collection->run()
#17 /.../my-project-01/vendor/consolidation/robo/src/Collection/CollectionBuilder.php(590): Robo\Collection\CollectionBuilder->runTasks()
#18 /.../my-project-01/vendor/consolidation/robo/src/Collection/CollectionProcessHook.php(30): Robo\Collection\CollectionBuilder->run()
#19 /.../my-project-01/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ProcessResultHookDispatcher.php(53): Robo\Collection\CollectionProcessHook->process()
#20 /.../my-project-01/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ProcessResultHookDispatcher.php(44): Consolidation\AnnotatedCommand\Hooks\Dispatchers\ProcessResultHookDispatcher->doProcessor()
#21 /.../my-project-01/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ProcessResultHookDispatcher.php(35): Consolidation\AnnotatedCommand\Hooks\Dispatchers\ProcessResultHookDispatcher->callProcessor()
#22 /.../my-project-01/vendor/consolidation/annotated-command/src/CommandProcessor.php(219): Consolidation\AnnotatedCommand\Hooks\Dispatchers\ProcessResultHookDispatcher->process()
#23 /.../my-project-01/vendor/consolidation/annotated-command/src/CommandProcessor.php(213): Consolidation\AnnotatedCommand\CommandProcessor->processResults()
#24 /.../my-project-01/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter()
#25 /.../my-project-01/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(313): Consolidation\AnnotatedCommand\CommandProcessor->process()
#26 /.../my-project-01/vendor/symfony/console/Command/Command.php(259): Consolidation\AnnotatedCommand\AnnotatedCommand->execute()
#27 /.../my-project-01/vendor/symfony/console/Application.php(920): Symfony\Component\Console\Command\Command->run()
#28 /.../my-project-01/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand()
#29 /.../my-project-01/vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun()
#30 /.../my-project-01/vendor/consolidation/robo/src/Runner.php(282): Symfony\Component\Console\Application->run()
#31 /.../my-project-01/vendor/consolidation/robo/src/Runner.php(158): Robo\Runner->run()
#32 /.../my-project-01/bin/pmkr(128): Robo\Runner->execute()
#33 {main}
```

**Comment by Sweetchuck** [comment]
This one solves the problem.
```patch
diff --git a/src/Task/Archive/Extract.php b/src/Task/Archive/Extract.php
index 817608a..bfc9669 100644
--- a/src/Task/Archive/Extract.php
+++ b/src/Task/Archive/Extract.php
@@ -4,10 +4,9 @@ namespace Robo\Task\Archive;
 
 use Robo\Result;
 use Robo\Task\BaseTask;
-use Robo\Task\Filesystem\FilesystemStack;
-use Robo\Task\Filesystem\DeleteDir;
+use Robo\Task\Filesystem\Tasks as FilesystemTaskLoader;
 use Robo\Contract\BuilderAwareInterface;
-use Robo\Common\BuilderAwareTrait;
+use Robo\TaskAccessor;
 
 /**
  * Extracts an archive.
@@ -34,7 +33,8 @@ use Robo\Common\BuilderAwareTrait;
  */
 class Extract extends BaseTask implements BuilderAwareInterface
 {
-    use BuilderAwareTrait;
+    use TaskAccessor;
+    use FilesystemTaskLoader;
 
     /**
      * @var string
@@ -129,16 +129,14 @@ class Extract extends BaseTask implements BuilderAwareInterface
             $filesInExtractLocation = glob("$extractLocation/*");
             $hasEncapsulatingFolder = ((count($filesInExtractLocation) == 1) && is_dir($filesInExtractLocation[0]));
             if ($hasEncapsulatingFolder && !$this->preserveTopDirectory) {
-                $result = (new FilesystemStack())
-                    ->inflect($this)
+                $this
+                    ->taskFilesystemStack()
                     ->rename($filesInExtractLocation[0], $this->to)
-                    ->run();
-                (new DeleteDir($extractLocation))
-                    ->inflect($this)
+                    ->remove($extractLocation)
                     ->run();
             } else {
-                $result = (new FilesystemStack())
-                    ->inflect($this)
+                $this
+                    ->taskFilesystemStack()
                     ->rename($extractLocation, $this->to)
                     ->run();
             }

```
