### ISSUE TITLE
taskExtract returns "Call to a member function newBuilder() on null"

### ISSUE THREAD

**Issue by borgogelli** [consolidation/Robo#573]
I use Robo (phar) 1.0.6 on Windows and I'm trying to unzip an archive with the folowing code:

`$this->taskExtract($archivePath)->to($destination)->run();`

But I get the following error:

```
>  ZIP: extracting z:\...\client.zip to z:\...\client ...
 [Archive\Extract] Extracting z:\...\client.zip
 [Archive\Extract] z:\...\client.zip extracted
 [Filesystem\FilesystemStack] _rename ["C:\\..../tmp7043639811494186034/client-master","z:\\....\\client"]
 1/1 [============================] 100%
 
 PHP Fatal error:  Uncaught Error: Call to a member function newBuilder() on null in phar://C:/..../robo.phar/src/Common/BuilderAwareTrait.php:43
 
Stack trace:
#0 phar://C:/..../robo.phar/src/Task/Filesystem/FilesystemStack.php(148): Robo\Task\Filesystem\FilesystemStack->collectionBuilder()
#1 phar://C:/..../robo.phar/src/Task/Filesystem/FilesystemStack.php(121): Robo\Task\Filesystem\FilesystemStack->crossVolumeRename('C:\\...', 'z:\\dev\\builds\\p...')
#2 [internal function]: Robo\Task\Filesystem\FilesystemStack->_rename('C:\\...', 'z:\\dev\\builds\\p...')
#3 phar://C:/..../robo.phar/src/Task/StackBasedTask.php(229): call_user_func_array(Array, Array)
#4 phar://C:/..../robo.phar/src/Task/StackBasedTask.php(206): Robo\Task\StackBasedTask->callTaskMethod(Array, Array)
#5 phar://C:/..../robo.phar/src/Task/Archive/Extract.php(131): Robo\Task\StackBasedTask- in phar://C:/..../robo.phar/src/Common/BuilderAwareTrait.php on line 43

Fatal error: Uncaught Error: Call to a member function newBuilder() on null in phar://C:/..../robo.phar/src/Common/BuilderAwareTrait.php:43

Stack trace:
#0 phar://C:/..../robo.phar/src/Task/Filesystem/FilesystemStack.php(148): Robo\Task\Filesystem\FilesystemStack->collectionBuilder()
#1 phar://C:/..../robo.phar/src/Task/Filesystem/FilesystemStack.php(121): Robo\Task\Filesystem\FilesystemStack->crossVolumeRename('C:\\...', 'z:\\...')
#2 [internal function]: Robo\Task\Filesystem\FilesystemStack->_rename('C:\\...', 'z:\\dev\\builds\\p...')
#3 phar://C:/..../robo.phar/src/Task/StackBasedTask.php(229): call_user_func_array(Array, Array)
#4 phar://C:/..../robo.phar/src/Task/StackBasedTask.php(206): Robo\Task\StackBasedTask->callTaskMethod(Array, Array)
#5 phar://C:/..../robo.phar/src/Task/Archive/Extract.php(131): Robo\Task\StackBasedTask- in phar://C:/..../robo.phar/src/Common/BuilderAwareTrait.php on line 43

ERROR: Uncaught Error: Call to a member function newBuilder() on null in phar://C:/..../robo.phar/src/Common/BuilderAwareTrait.php:43

Stack trace:
#0 phar://C:/..../robo.phar/src/Task/Filesystem/FilesystemStack.php(148): Robo\Task\Filesystem\FilesystemStack->collectionBuilder()
#1 phar://C:/..../robo.phar/src/Task/Filesystem/FilesystemStack.php(121): Robo\Task\Filesystem\FilesystemStack->crossVolumeRename('C:...', 'z:\\...')
#2 [internal function]: Robo\Task\Filesystem\FilesystemStack->_rename('C:\\...', 'z:\\...')
#3 phar://C:/..../robo.phar/src/Task/StackBasedTask.php(229): call_user_func_array(Array, Array)
#4 phar://C:/..../robo.phar/src/Task/StackBasedTask.php(206): Robo\Task\StackBasedTask->callTaskMethod(Array, Array)
#5 phar://C:/..../robo.phar/src/Task/Archive/Extract.php(131): Robo\Task\StackBasedTask-in phar://C:/..../robo.phar/src/Common/BuilderAwareTrait.php:43
```

**Comment by soap** [comment]
I also encountered this problem when upgrade from "codegyre/robo" to "consolidation/robo". Any solution exists?

**Comment by greg-1-anderson** [comment]
I think that there is a working test for taskExtract that passes on AppVeyor. Perhaps someone could isolate the difference between the passing test and the observed failure.

**Comment by dafeder** [comment]
Just encountered the same issue.

**Comment by dafeder** [comment]
I was going a little crazy debugging this and then I realized that there was simply a typo in the code that generated the argument passed to `to()`. Seems like it should fail a little more gracefully but seems to work as expected if passed valid values.

**Comment by nassaz** [comment]
@dafeder what do you mean please by "valid values" ?
