### ISSUE TITLE
Url inside a phpdoc block: "ERROR: is not a valid Fqsen"

### ISSUE THREAD

**Issue by borgogelli** [consolidation/Robo#579]
Hello
I use Robo 1.0.6 (phar distro)

When I use the following phpdoc:
```
/**
* @see http//svnbook.red-bean.com/en/1.7/svn.ref.svn.c.export.html
*/
public function exportAll{
....
}
```

I get

```
ERROR: Uncaught InvalidArgumentException: "\https://svnbook.red-bean.com/en/1.7/svn.ref.svn.c.export.html" is not a valid Fqsen. in phar://.../robo.phar/vendor/phpdocumentor/reflection-common/src/Fqsen.php:44
Stack trace:
#0 phar://.../robo.phar/vendor/phpdocumentor/type-resolver/src/FqsenResolver.php(69): phpDocumentor\Reflection\Fqsen->__construct('\\https://svnboo...')
#1 phar://.../robo.phar/vendor/phpdocumentor/type-resolver/src/FqsenResolver.php(32): phpDocumentor\Reflection\FqsenResolver->resolvePartialStructuralElementName('https://svnbook...', Object(phpDocumentor\Reflection\Types\Context))
#2 phar://.../robo.phar/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/See.php(59): phpDocumentor\Reflection\FqsenResolver->resolve('https://svnbook...', Object(phpDocumentor\Reflection\Types\Context))
#3 [internal function]: phpDocumentor\Reflection\DocBlock\Tags\See::create('https://svnbook...
in phar://.../robo.phar/vendor/phpdocumentor/reflection-common/src/Fqsen.php:44
```

**Comment by greg-1-anderson** [comment]
See the [@see tag documentation](https://www.phpdoc.org/docs/latest/references/phpdoc/tags/see.html). @see may take either a URI or a FQSEN. Your URI has a typo; correct it to "http://", and this problem should go away.
