### ISSUE TITLE
TaskForEach::withBuilder with empty array throws an exception

### ISSUE THREAD

**Issue by Sweetchuck** [consolidation/robo#655]
### Steps to reproduce
```php
<?php
class RoboFile extends \Robo\Tasks {

    public function loopD()
    {
        $items = [];

        return $this
            ->taskForEach($items)
            ->withBuilder(function (CollectionBuilder $builder, string $key, $value) {
                $builder->addCode(function () use ($key, $value) {
                    $this->say("key = $key");
                    $this->say("value = $value");
                });
            });
    }
}
```

`$ vendor/bin/robo loop:d`

### Expected behavior
Empty stdOutput

### Actual behavior
```
Fatal error: Uncaught TypeError: Argument 2 passed to RoboFile::{closure}() must be of the type string, null given in /projectRoot/RoboFile.php on line 578

TypeError: Argument 2 passed to RoboFile::{closure}() must be of the type string, null given in /projectRoot/RoboFile.php on line 578

Call Stack:
    0.0079     411312   1. {main}() /projectRoot/vendor/consolidation/robo/robo:0
    0.1180     496568   2. Robo\Runner->execute(???, ???, ???, ???) /projectRoot/vendor/consolidation/robo/robo:21
    0.1264     755568   3. Robo\Runner->run(???, ???, ???, ???) /projectRoot/vendor/consolidation/robo/src/Runner.php:123
    0.1923    1939024   4. Robo\Application->run(???, ???) /projectRoot/vendor/consolidation/robo/src/Runner.php:175
    0.1976    1953072   5. Robo\Application->doRun(???, ???) /projectRoot/vendor/symfony/console/Application.php:148
    0.1978    1953072   6. Robo\Application->doRunCommand(???, ???, ???) /projectRoot/vendor/symfony/console/Application.php:240

ERROR: Uncaught TypeError: Argument 2 passed to RoboFile::{closure}() must be of the type string, null given in /projectRoot/RoboFile.php:578
Stack trace:
#0 [internal function]: RoboFile->{closure}(Object(Robo\Collection\CollectionBuilder), NULL, false)
#1 /projectRoot/vendor/consolidation/robo/src/Collection/TaskForEach.php(120): call_user_func(Object(Closure), Object(Robo\Collection\CollectionBuilder), NULL, false)
#2 [internal function]: Robo\Collection\TaskForEach->Robo\Collection\{closure}(NULL, false)
#3 /projectRoot/vendor/consolidation/robo/src/Collection/TaskForEach.php(156): call_user_func(Object(Closure), NULL, false)
#4 /projectRoot/vendor/consolidation/robo/src/Collection/Element.php(108): Robo\Collection\TaskForEach->progressIndicatorSteps()
#5 /projectRoot/vendor/c 
in /projectRoot/RoboFile.php:578
```

### System Configuration
PHP 7.1.10
consolidation/robo 1.1.5

**Comment by Sweetchuck** [comment]
The issue was reported for Robo 1.x. I assume that it is not maintained any more, and the mentioned problem is not reproducible with Robo 3.x.
